name: Export Check

on:
  push:
  pull_request:
    branches: ['main']

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js
        uses: actions/setup-node@v2
      - name: Check npm version
        run: npm -v
      - name: Install dependencies 🔨
        run: ci install
      - name: Build 🏗️
        run: npm run export