name: Next Deploy GH Page
on:
  push:
    branches:
      - main
jobs:k
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Install and Build 🔧
        run: |
          npm ci
          npm run export
      - name: Deploy 🚀
        uses: JamesIves/github-pages-deploy-action@4.1.4
        with:
          branch: gh-pages
          folder: out